name: DotnetXunitTestDemo

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x # Specify your .NET Core version here

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the application
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Step 5: Run tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    # Step 6: Publish build artifacts (optional)
    - name: Publish Artifact
      if: success()
      run: dotnet publish -c Release -o ./output

    # Step 7: Upload build artifact (optional)
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./output
