name: DotnetXunitTestDemo

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set execute permissions for the shell script
    - name: Set execute permissions for the shell script
      run: chmod +x Scripts/Notifier.sh

    # Install sendmail utility
    - name: Install sendmail
      run: sudo apt-get install -y sendmail

    # Run the shell script to send an email
    - name: Send email notification
      run: ./Scripts/Notifier.sh ${{ secrets.TO_EMAIL }}
      env:
        TO_EMAIL: ${{ secrets.TO_EMAIL }}

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Clear NuGet cache
    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore DotnetXunitTestDemo/DotnetXunitTestDemo.sln --source "https://api.nuget.org/v3/index.json"

    # Run Tests
    - name: Run Tests
      run: dotnet test DotnetXunitTestDemo/DotnetXunitTestDemo.sln --no-restore --verbosity normal

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore DotnetXunitTestDemo/DotnetXunitTestDemo.sln --source "https://api.nuget.org/v3/index.json"

    - name: Build
      run: dotnet build DotnetXunitTestDemo/DotnetXunitTestDemo.sln --configuration Release --no-restore

    - name: Publish Artifact
      run: dotnet publish DotnetXunitTestDemo/DotnetXunitTestDemo.sln -c Release -o ./output

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./output
