name: DotnetXunitTestDemo

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x # Specify your .NET Core version here

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore DotnetXunitTestDemo/DotnetXunitTestDemo.sln

    # Step 4: Run tests
    - name: Run Tests
      run: dotnet test DotnetXunitTestDemo/DotnetXunitTestDemo.sln --no-restore --verbosity normal

  build:
    runs-on: ubuntu-latest
    needs: test  # This job will only run if the test job succeeds

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x # Specify your .NET Core version here

    # Step 3: Build the application
    - name: Build
      run: dotnet build DotnetXunitTestDemo/DotnetXunitTestDemo.sln --configuration Release --no-restore

    # Step 4: Publish build artifacts
    - name: Publish Artifact
      run: dotnet publish DotnetXunitTestDemo/DotnetXunitTestDemo.sln -c Release -o ./output

    # Step 5: Upload build artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./output
